### ISSUE TITLE
R-devel crashes on Windows 2022

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/archive#68]
With libarchive 3.3.3.

This is from `example(archive_read)`:

```
(gdb) bt 10
#0  0x00007ffe10a15f31 in ucrtbase!strlen ()
   from C:\WINDOWS\System32\ucrtbase.dll
#1  0x00007ffdd3da8bab in archive!_ZNK5cpp118functionclIJRNS_8writable8r_vectorIP7SEXPRECEEEEENS_4sexpEDpOT_ ()
   from C:\Users\csard\AppData\Local\R\win-library\4.2\archive\libs\x64\archive.dll
#2  0x00007ffdd3bfd558 in archive!_Z13archive_read_N5cpp114sexpES0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_NS_8r_vectorIiEESA_NS9_INS_8r_stringEEEy ()
   from C:\Users\csard\AppData\Local\R\win-library\4.2\archive\libs\x64\archive.dll
#3  0x00007ffd8e3f711a in R_gzclose ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#4  0x00007ffd8e45b674 in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#5  0x00007ffd8e474941 in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#6  0x00007ffd8e47a00c in R_cmpfun1 ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#7  0x00007ffd8e47b41a in Rf_applyClosure ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#8  0x00007ffd8e4b86aa in R_has_methods_attached ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#9  0x00007ffd8e4b8a0d in R_has_methods_attached ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
```

This is from `devtools::test()`:

```
(gdb) bt 10
#0  0x00007ffe10a15f31 in ucrtbase!strlen ()
   from C:\WINDOWS\System32\ucrtbase.dll
#1  0x00007ffd8e446233 in Rf_mkCharCE ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#2  0x00007ffd8e404fbc in R_UnwindProtect ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#3  0x00007ffdd30102a8 in archive!_ZN5cpp1114unwind_protectINS_6detail7closureIFP7SEXPRECPKc8cetype_tEJRS6_OS7_EEEvEES4_OT_ ()
   from C:\Users\csard\AppData\Local\Temp\Rtmpwvlfxs\pkgload312050124303\archive.dll
#4  0x00007ffdd2e697a6 in archive!_Z16archive_extract_RKN5cpp114sexpES0_iNS_8r_vectorINS_8r_stringEEEy ()
   from C:\Users\csard\AppData\Local\Temp\Rtmpwvlfxs\pkgload312050124303\archive.dll
#5  0x00007ffdd2e73e7e in archive!_archive_archive_extract_ ()
   from C:\Users\csard\AppData\Local\Temp\Rtmpwvlfxs\pkgload312050124303\archive.dll
#6  0x00007ffd8e416a93 in Rf_NewFrameConfirm ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#7  0x00007ffd8e4171ed in Rf_NewFrameConfirm ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#8  0x00007ffd8e474f43 in R_initAssignSymbols ()
   from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
#9  0x00007ffd8e47577b in Rf_eval () from C:\PROGRA~1\R\R-devel\bin\x64\R.dll
(More stack frames follow...)
```

**Comment by gaborcsardi** [comment]
Fixed by patching libarchive to better support UTF-8 on Windows: https://github.com/r-windows/rtools-packages/commit/5f081b5e464fbb2eef47d575aae13248463eb370

All credits belong to @jeroen!
